### ISSUE TITLE
[FEATURE REQUEST] how to style the button?

### ISSUE THREAD

**Issue by wmaiouiru** [gdowens/react-toggle-button#5]
Is there any easy way to style the button? For example, change the width and the height?

**Comment by sonali-moholkar** [comment]
any update on this one?

**Comment by nemax23** [comment]
Inspecting the code you can understand how to change the style.  For example to change the width of the entire toggle to 100 px (instead of default 52):

`<ToggleButton value={...}
 containerStyle={{display:'inline-block',width:'100px'}} trackStyle={{width:'100px'}}       thumbAnimateRange={[1, 80]} activeLabelStyle={{ width:'50px' }} inactiveLabelStyle={{ width:'50px' }}></ToggleButton>
`

which is, set containerStyle and trackStyle  width to your X (100), set active and inactive width to X/2 (50), set the animate range which moves the thumb to 1 ... X - size of the thumb (by default  18px) - any padding (100-18-2=80)
